name: Run pytest

on:
  workflow_dispatch:

jobs:
  pytest:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run pytest
        run: |
          python -m pytest --junit-xml results/pytest.xml
        continue-on-error: true

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: test_results
          path: results/*.xml

      - name: Download results
        uses: actions/download-artifact@v3
        with:
          name: test_results
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: artifacts/**/*.xml
